#!/bin/bash

# Número de drones que deseas lanzar
num_drones=4

# Ruta al script del dron
script_path="EC_Customer.py"

BROKER_IP="localhost"
BROKER_PORT=20000

for ((i=0; i<=$num_drones; i++))
do
    ID=$(printf "\\$(printf '%03o' $((97 + i)))") # 97 es el ASCII de 'a'

    gnome-terminal --tab --title="Cliente_$ID" -- python3 $script_path $BROKER_IP $BROKER_PORT $ID

    sleep 1
done
